### ISSUE TITLE
Version for v10?

### ISSUE THREAD

**Issue by eqms** [WilldooIT/Pentaho-Odoo#5]
Hi,

I just tested the committed modules, but I can't connect from designer via xmlrpc.
Is there a timeline till that will be work?

I can also donate your work if that speed up the time.

We have created all reports for the German Look&Feel https://github.com/equitania/odoo-pentaho/tree/8.0/modules/reports for v8 and want to port them also to v10.

**Comment by richard-willdooit** [comment]
@eqms Version 11 and 12 are coming soon
